@CarRental_HostAddress = http://localhost:5199

###
GET {{CarRental_HostAddress}}/api/carrental
Accept: application/json

###
GET {{CarRental_HostAddress}}/api/carrental/4
Accept: application/json

###
POST {{CarRental_HostAddress}}/api/carrental
Content-Type: application/json

{
    "name": "Sedan",
    "cost": 1950,
    "available": true
}

###
PUT {{CarRental_HostAddress}}/api/carrental/4
Content-Type: application/json

{
    "id": 4,
    "name": "GenericCar",
    "cost": 1950,
    "available": false
}

###
DELETE {{CarRental_HostAddress}}/api/carrental/2