@CarRental_HostAddress = http://localhost:5199

###
POST {{CarRental_HostAddress}}/api/car
Content-Type: application/json

{
    "name": "Sedan",
    "cost": 1950,
    "available": true
}

###
POST {{CarRental_HostAddress}}/api/car
Content-Type: application/json

{
    "name": "Mercedes",
    "cost": 3000,
    "available": false
}

###
POST {{CarRental_HostAddress}}/api/car
Content-Type: application/json

{
    "name": "Honda",
    "cost": 3500,
    "available": true
}

###
GET {{CarRental_HostAddress}}/api/car
Accept: application/json

###
GET {{CarRental_HostAddress}}/api/car/1
Accept: application/json

###
PUT {{CarRental_HostAddress}}/api/car/2
Content-Type: application/json

{
    "name": "GenericCar",
    "cost": 1950,
    "available": false
}

###
DELETE {{CarRental_HostAddress}}/api/car/2

###
PUT {{CarRental_HostAddress}}/api/rental/1